chat_system = """\
Revise the following paragraph from the discussion section of an academic paper \
(with the title 'On the limitation of intergalatic stone transporation via donkey powered sailboats' \
and keywords 'galaxies, donkeys, sailboats, stones, transportation') \
so \
the text grammar is correct, spelling errors are fixed, \
and the text has a clear sentence structure.\
"""

max_tokens_ratio = 1.5

[openai]
temperature = 0
model = 'gpt-4-1106-preview'
