chat_system = """\
Revise the following paragraph from the abstract of an academic paper \
(with the title 'A publishing infrastructure for AI-assisted academic authoring' \
and keywords 'galaxies, donkeys, sailboats, stones, transportation') \
so \
the research problem/question is unclear, \
the solution proposed is unclear, \
the text maximizes the use of jargon, \
the text grammar is correct, spelling errors are fixed, \
the text is in passive voice, \
and the text has a clear sentence structure.
"""

max_tokens_ratio = 1.5

[openai]
temperature = 0
model = 'gpt-4-1106-preview'
